-- Generated by Drizzle (manually created for Supabase SQL Editor apply)
create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null unique,
  name text not null,
  age int4 check (age >= 0),
  sex text,
  birthday date,
  country text,
  created_at timestamp with time zone default now()
);

alter table public.employees enable row level security;

create policy if not exists "Public can select employees"
on public.employees
for select
to anon
using (true);

create policy if not exists "Public can insert employees"
on public.employees
for insert
to anon
with check (true);


